import numpy as np
TOTAL_BITS = 16
FRAC_BITS  = 8
SCALE      = 1 << FRAC_BITS   

np.random.seed(0)

A_float = np.random.uniform(-2.0, 2.0, size=(16, 4))
B_float = np.random.uniform(-2.0, 2.0, size=(4, 16))

#change this to 16 bit fixed point Q16.0 integer
A_fixed = np.round(A_float * SCALE).astype(np.int16)
B_fixed = np.round(B_float * SCALE).astype(np.int16)

with open("a_file.txt", "w") as f:
    for val in A_fixed.flatten():
        f.write(f"{int(val)}\n")

with open("b_file.txt", "w") as f:
    for val in B_fixed.T.flatten():
        f.write(f"{int(val)}\n")

print("Generated fixed-point inputs:")
print("A_fixed shape:", A_fixed.shape)
print("B_fixed shape:", B_fixed.shape)

print("\nvalues of a_file.txt:")
print(A_fixed.flatten())

print("\nvalues of b_file.txt:")
print(B_fixed.T.flatten())
INT16_MAX =  32767
INT16_MIN = -32768
def sat16(x):
    if x > INT16_MAX:
        return INT16_MAX
    elif x < INT16_MIN:
        return INT16_MIN
    else:
        return int(x)

# load
A = np.loadtxt("a_file.txt", dtype=int).reshape(16, 4)          # 16x4
B = np.loadtxt("b_file.txt", dtype=int).reshape(16, 4).T        # 4x16
C_dut = np.loadtxt("c_out_file.txt", dtype=int).reshape(-1)     # 256

##NOTE: I GOT c_out_file.txt from vivado
print(A)
print(B)

C = np.zeros((16, 16), dtype=np.int64)
for i in range(16):
    for j in range(16):
        acc = 0
        for k in range(4):
            acc += int(A[i, k]) * int(B[k, j])  # Q16.0
        C[i, j] = sat16(acc)

# flatten into 1D array so we can compare with the file generated by DUT
C_gold = []
for tr in range(0, 16, 4):
    for tc in range(0, 16, 4):
        for i in range(4):
            for j in range(4):
                C_gold.append(int(C[tr+i, tc+j]))
C_gold = np.array(C_gold, dtype=int)

# compare
mismatch = 0

for i in range(len(C_dut)):
    if C_dut[i] == C_gold[i]:
        print(f"addr {i}: DUT={C_dut[i]} GOLD={C_gold[i]} EQUAL")
    else:
        mismatch +=1
        print(f"addr {i}: DUT={C_dut[i]} GOLD={C_gold[i]} WRONG")

print(f"number of mismatch = {mismatch}")
